const gallery = document.getElementById("gallery");

const imageList = [
  "3gatsu_no_lion.jpeg",
  "20th-century-boys.jpeg",
  "air_gear1.jpeg",
  "air_gear2.jpeg",
  "Akame_ga_Kill!.jpeg",
  "another.jpeg",
  "ashita-no-joe1.jpeg",
  "ashita-no-joe2.jpeg",
  "Assassination_Classroom.jpeg",
  "Attack titan vs Armored titan (wallpaper).jpeg",
  "bakuman.jpeg",
  "barakamon.jpeg",
  "beelzebub.jpeg",
  "berserk.jpeg",
  "Black Clover.jpeg",
  "Bleach.jpeg",
  "Blue_Exorcist.jpeg",
  "blue_lock.jpeg",
  "bocchi-the-rock.jpeg",
  "btooom.jpeg",
  "Chainsaw Man.jpeg",
  "claymore.jpeg",
  "cowboy-bebop.jpeg",
  "dandadan.jpeg",
  "deadman_wonderland.jpeg",
  "Death_Note.jpeg",
  "demon_slayer.jpeg",
  "dgray-man.jpeg",
  "dr_stone.jpeg",
  "dragonball.jpeg",
  "dungeon-meshi.jpeg",
  "fairytail.jpeg",
  "fire_force.jpeg",
  "fruits-basket.jpeg",
  "fullmetal-alchemist.jpeg",
  "gantz.jpeg",
  "gintama.jpeg",
  "grand-blue.jpeg",
  "great_teacher_onizuka.jpeg",
  "guimi-zhi-zhu.jpeg",
  "hellsing.jpeg",
  "hunterXhunter.jpeg",
  "jojo.jpeg",
  "Jujutsu-Kaisen-Vol.-7.png",
  "kaguya-sama1.jpeg",
  "kaguya-sama2.jpeg",
  "kekkai_sensen.jpeg",
  "koe-no-katachi.jpeg",
  "Magi.jpeg",
  "mashle.jpeg",
  "medaka_box.jpeg",
  "mob-psycho-100.jpeg",
  "monster.jpeg",
  "My-Hero-Academia-Vol.-29.png",
  "Naruto HD Cover Photo.jpeg",
  "noragami.jpeg",
  "One_Punch_Man.jpeg",
  "onepiece.jpeg",
  "oshinoko.jpeg",
  "oyasumi-punpun.jpeg",
  "reborn.jpeg",
  "rosario_plus_vampire.jpeg",
  "rurouni_kenshin.jpeg",
  "shaman_king.jpeg",
  "slam-dunk.jpeg",
  "solo_leveling.jpeg",
  "sousou-no-frieren.jpeg",
  "SPY x FAMILY.jpeg",
  "steins-gate.jpeg",
  "the_breaker.jpeg",
  "The-Promised-Neverland-Vol.-5.png",
  "Tokyo Revengers.jpeg",
  "toradora.jpeg",
  "TORIKO.jpeg",
  "uq_holder.jpeg",
  "vagabond1.jpeg",
  "vagabond2.jpeg",
  "vinland _saga.jpeg",
  "yamada-kun_and_the_seven_witches.jpeg",
  "yotsuba-to.jpeg",
  "zetman.jpeg"
];


imageList.forEach(filename => {
  const img = document.createElement("img");
  img.src = `img/${filename}`;
  img.alt = filename;
  gallery.appendChild(img);
});
